### ISSUE TITLE
Fix lodash vulnerabilities

### ISSUE THREAD

**Issue by Blackvz** [fabien0102/config-manager#1]
You should update lodash to fix the vulnerabilities

**Comment by fabien0102** [comment]
I can ^^ after since the config values are just used by your code and can't be modified by user inputs, the project is not affect by the security issue 😉

But I'm glad to see that someone is still using this old simple tool, so let's remove this ugly warning 😁

**Comment by fabien0102** [comment]
Done! I removed lodash in favor of more modern javascript feature 😁

PS: I didn't touch a javascript only project since a long time ^^ I would probably re-write this library in typescript if I go back to backend development one day, auto-completion on config is just amazing 😀 My most recent config library for react -> https://github.com/contiamo/react-runtime-config (I don't know why, I never found something that fit my need regarding configuration 🙄)
